// ***********************************************************************
//  Assembly         : RzR.Shared.eGovMD.MPassHelperDotNet
//  Author           : RzR
//  Created On       : 2023-06-23 14:44
// 
//  Last Modified By : RzR
//  Last Modified On : 2023-06-28 16:26
// ***********************************************************************
//  <copyright file="GetUserDataFromAuthResponseDto.cs" company="">
//   Copyright (c) RzR. All rights reserved.
//  </copyright>
// 
//  <summary>
//  </summary>
// ***********************************************************************

// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable ClassNeverInstantiated.Global

namespace MPassHelperDotNet.Models.Dto.AuthService.LoginResponse
{
    /// <summary>
    ///     Get user profile information
    /// </summary>
    public class GetUserDataFromAuthResponseDto
    {
        /// <summary>
        ///     SAMLResponse message received from auth service provider
        /// </summary>
        public string SamlResponse { get; set; }

        /// <summary>
        ///     Authentication request id.
        ///     Also generated by <see cref="MPassHelperDotNet.Abstractions.Services.IAuthMPassService.GenerateAuthRequestAsync" /> method.
        /// </summary>
        public string AuthRequestId { get; set; }
    }
}